apiVersion: v1
kind: Secret
metadata:
  name: micro-backend-secret
  namespace: production
type: Opaque
data:
  secret-key-one: MDMyYzVjM2NmYzM3OTM4YWU2ZGQ0M2QzYTNlYzc4MzQ=
  secret-key-two: ZDY2ZTM3NzAxOGMwYmMwYjU3NzJiYmM5YjEzMWU2ZDk=
  gateway-jwt-token: MTI4MjcyMmI5NDJlMDhjOGE2Y2IwMzNhYTZjZTg1MGU=
  jwt-token: OGRiOGY4NTk5MWJiMjhmNDVhYzAxMDdmMmExYjM0OWM=
  micro-redis-host: cmVkaXM6Ly86dGhpc2lzbXlvd25wYXNzd29yZDEyM0BAbWljcm8tcmVkaXMtcHJvZHVjdGlvbi5zdmMuY2x1c3Rlci5sb2NhbDo2Mzc5
  sender-email: ZmVsaWNpdGF0QGV0aGVycmVhbC5lbWFpbA==
  sender-email-password: VlhoZnBhc21SN2p6ZDNzeWJD
  micro-mysql-db: bXlzcWw6Ly9taWNyb2dyYWRlOmFwaUBtaWNyby1teXNxbC5wcm9kdWN0aW9uLnN2Yy5jbHVzdGVyLmxvY2FsOjMzMDYvbWljcm9ncmFkZV9hdXRo
  micro-postgres-host: bWljcm8tcG9zdGdyZXMucHJvZHVjdGlvbi5zdmMuY2x1c3Rlci5sb2NhbA==
  micro-postgres-user: bWljcm9ncmFkZQ==
  micro-postgres-password: YXBp
  cloud-name: ZHluYW1pYzl5bTM=
  cloud-api-key: MjgyNzgyODY0MTgyOTI0
  cloud-api-secret: SlVYeHJfaHpjUUh1dWdzNXR6QjVhU1RDaEFV
  mongo-database-url: bW9uZ29kYjovL21pY3JvLW1vbmdvLnByb2R1Y3Rpb24uc3ZjLmNsdXN0ZXIubG9jYWw6MjcwMTcvbWljcm9ncmFkZQ==
  stripe-api-key: cGtfdGVzdF81MU9xaFRvQjRFdHZRQ2FidnZsZ3RVZFhFYTQ3SndRV0hhVXJXZm01b2hlTVA0eXg0MnpmRm9jNXg0eDF6TVlseGRDT1paS0syMGFpeWZxUFBXaDFwZGlTdzAwRVRYSzJEaVg=
  micro-rabbitmq-user: bWljcm9ncmFkZQ==
  micro-rabbitmq-password: bWljcm9ncmFkZXBhc3M=
  micro-rabbitmq-endpoint: YW1xcDovL21pY3JvZ3JhZGU6bWljcm9ncmFkZXBhc3NAbWljcm8tcXVldWUucHJvZHVjdGlvbi5zdmMuY2x1c3Rlci5sb2NhbDo1Njcy
  micro-elasticsearch-url: aHR0cDovL2VsYXN0aWM6YWRtaW4xMjM0QG1pY3JvLWVsYXN0aWMucHJvZHVjdGlvbi5zdmMuY2x1c3Rlci5sb2NhbDo5MjAw
  micro-elastic-apm-server-url: ""
  micro-elastic-apm-secret-token: ""
  micro-elasticsearch-host: bWljcm8tZWxhc3RpYy5wcm9kdWN0aW9uLnN2Yy5jbHVzdGVyLmxvY2Fs
  micro-elasticsearch-username: ZWxhc3RpYw==
  micro-elasticsearch-password: YWRtaW4xMjM0
