apiVersion: apps/v1
kind: Deployment
metadata:
  name: micro-kibana
  namespace: production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: micro-kibana
  template:
    metadata:
      labels:
        app: micro-kibana
    spec:
      containers:
        - name: micro-kibana
          image: docker.elastic.co/kibana/kibana:8.11.0
          resources:
            limits:
              memory: "1Gi"
              cpu: "1500m"
            requests:
              cpu: 250m
              memory: 1Gi
          env:
            - name: ELASTICSEARCH_HOSTS
              # http://<service-name>.<namespace>.svc.cluster.local:<port-number>
              value: http://micro-elastic.production.svc.cluster.local:9200
            - name: ELASTICSEARCH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: micro-backend-secret
                  key: micro-elasticsearch-password
          ports:
            - name: micro-kibana
              containerPort: 5601
