apiVersion: v1
kind: Service
metadata:
  name: micro-auth
  namespace: production
spec:
  type: ClusterIP
  selector:
    app: micro-auth
  ports:
    - name: auth
      port: 4002
      targetPort: 4002
      protocol: TCP
