apiVersion: v1
kind: Service
metadata:
  name: micro-postgres
  namespace: production
spec:
  type: ClusterIP
  selector:
    app: micro-postgres
  ports:
    - name: micro-postgres
      port: 5432
      targetPort: 5432
