apiVersion: apps/v1
kind: Deployment
metadata:
  name: micro-postgres
  namespace: production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: micro-postgres
  template:
    metadata:
      labels:
        app: micro-postgres
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: micro-postgres
          image: postgres:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: POSTGRES_USER
              value: micro
            - name: POSTGRES_PASSWORD
              value: api
            - name: POSTGRES_DB
              value: micro_reviews
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          resources:
            limits:
              memory: "1Gi"
              cpu: "0.5"
            requests:
              cpu: 100m
              memory: 150Mi
          ports:
            - name: micro-postgres
              containerPort: 5432
          volumeMounts:
            - name: postgres-local-storage
              mountPath: /var/lib/postgresql/data
              subPath: postgres
          readinessProbe:
            exec:
              command:
                [
                  "psql",
                  "-w",
                  "-U",
                  "micro",
                  "-d",
                  "micro_reviews",
                  "-c",
                  "SELECT 1",
                ]
            initialDelaySeconds: 120
            periodSeconds: 300
            timeoutSeconds: 60
          livenessProbe:
            exec:
              command:
                [
                  "psql",
                  "-w",
                  "-U",
                  "micro",
                  "-d",
                  "micro_reviews",
                  "-c",
                  "SELECT 1",
                ]
            initialDelaySeconds: 120
            periodSeconds: 300
            timeoutSeconds: 60
      volumes:
        - name: postgres-local-storage
          persistentVolumeClaim:
            claimName: postgres-pvc
