apiVersion: apps/v1
kind: Deployment
metadata:
  name: micro-review
  namespace: production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: micro-review
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: micro-review
    spec:
      containers:
        - name: micro-review
          image: remus1504/microreview:stable
          imagePullPolicy: Always
          resources:
            limits:
              memory: "1Gi"
              cpu: "0.5"
            requests:
              cpu: 100m
              memory: 150Mi
          ports:
            - name: review
              containerPort: 4007
          env:
            - name: ENABLE_APM
              value: "1"
            - name: NODE_ENV
              value: "production"
            - name: CLUSTER_TYPE
              value: "minikube"
            - name: GATEWAY_JWT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: micro-backend-secret
                  key: gateway-jwt-token
            - name: JWT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: micro-backend-secret
                  key: jwt-token
            - name: RABBITMQ_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: micro-backend-secret
                  key: micro-rabbitmq-endpoint
            - name: DATABASE_HOST
              valueFrom:
                secretKeyRef:
                  name: micro-backend-secret
                  key: micro-postgres-host
            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: micro-backend-secret
                  key: micro-postgres-user
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: micro-backend-secret
                  key: micro-postgres-password
            - name: DATABASE_NAME
              value: "micro_reviews"
            - name: CLOUD_NAME
              valueFrom:
                secretKeyRef:
                  name: micro-backend-secret
                  key: cloud-name
            - name: CLOUD_API_KEY
              valueFrom:
                secretKeyRef:
                  name: micro-backend-secret
                  key: cloud-api-key
            - name: CLOUD_API_SECRET
              valueFrom:
                secretKeyRef:
                  name: micro-backend-secret
                  key: cloud-api-secret
            - name: API_GATEWAY_ENDPOINT
              value: "http://micro-gateway.production.svc.cluster.local:4000"
            - name: ELASTIC_SEARCH_URL
              valueFrom:
                secretKeyRef:
                  name: micro-backend-secret
                  key: micro-elasticsearch-url
            - name: ELASTIC_APM_SERVER_URL
              valueFrom:
                secretKeyRef:
                  name: micro-backend-secret
                  key: micro-elastic-apm-server-url
            - name: ELASTIC_APM_SECRET_TOKEN
              valueFrom:
                secretKeyRef:
                  name: micro-backend-secret
                  key: micro-elastic-apm-secret-token
