apiVersion: v1
kind: Service
metadata:
  name: micro-course
  namespace: production
spec:
  type: ClusterIP
  selector:
    app: micro-course
  ports:
    - name: course
      port: 4004
      targetPort: 4004
      protocol: TCP
