apiVersion: v1
kind: Service
metadata:
  name: micro-mysql
  namespace: production
spec:
  type: ClusterIP
  selector:
    app: micro-mysql
  ports:
    - name: micro-mysql
      port: 3306
      targetPort: 3306
