apiVersion: v1
kind: Service
metadata:
  name: micro-enrolment
  namespace: production
spec:
  type: ClusterIP
  selector:
    app: micro-enrolment
  ports:
    - name: order
      port: 4006
      targetPort: 4006
      protocol: TCP
